### ISSUE TITLE
When test data is large，the code can‘t work and occur overflow probem

### ISSUE THREAD

**Issue by HuangZuShu** [dshea89/SubsetTree#1]
public static int choose( int n, int k ) {
    return ( factorial( n ) / ( factorial( k ) * factorial( n - k ) ) );
  }

**Comment by dshea89** [comment]
This function has been updated, you can try again.

https://github.com/dshea89/SubsetTree/blob/d0e61238d623eb2d46868ad1febf6f2d6595e5a6/SubsetSum.java#L273

If it still fails, please provide more information, such as the specific test case.

**Comment by HuangZuShu** [comment]
> This function has been updated, you can try again.
> 
> https://github.com/dshea89/SubsetTree/blob/d0e61238d623eb2d46868ad1febf6f2d6595e5a6/SubsetSum.java#L273
> 
> If it still fails, please provide more information, such as the specific test case.

Thank you for you help，I try it again.
